// Arabic word list with categories for hints - 500+ words
export interface WordData {
  word: string
  category: string
}

export const ARABIC_WORDS: WordData[] = [
  // طبيعة - Nature (50 words)
  { word: 'شمس', category: 'طبيعة' },
  { word: 'قمر', category: 'طبيعة' },
  { word: 'بحر', category: 'طبيعة' },
  { word: 'جبل', category: 'طبيعة' },
  { word: 'شجرة', category: 'طبيعة' },
  { word: 'زهرة', category: 'طبيعة' },
  { word: 'نهر', category: 'طبيعة' },
  { word: 'سماء', category: 'طبيعة' },
  { word: 'نجم', category: 'طبيعة' },
  { word: 'غابة', category: 'طبيعة' },
  { word: 'صحراء', category: 'طبيعة' },
  { word: 'وادي', category: 'طبيعة' },
  { word: 'شلال', category: 'طبيعة' },
  { word: 'بركان', category: 'طبيعة' },
  { word: 'كهف', category: 'طبيعة' },
  { word: 'تل', category: 'طبيعة' },
  { word: 'سهل', category: 'طبيعة' },
  { word: 'واحة', category: 'طبيعة' },
  { word: 'ثلج', category: 'طبيعة' },
  { word: 'مطر', category: 'طبيعة' },
  { word: 'برق', category: 'طبيعة' },
  { word: 'رعد', category: 'طبيعة' },
  { word: 'ريح', category: 'طبيعة' },
  { word: 'عاصفة', category: 'طبيعة' },
  { word: 'ضباب', category: 'طبيعة' },
  { word: 'غيوم', category: 'طبيعة' },
  { word: 'قوس', category: 'طبيعة' },
  { word: 'فجر', category: 'طبيعة' },
  { word: 'غروب', category: 'طبيعة' },
  { word: 'ليل', category: 'طبيعة' },
  { word: 'نهار', category: 'طبيعة' },
  { word: 'خريف', category: 'طبيعة' },
  { word: 'ربيع', category: 'طبيعة' },
  { word: 'صيف', category: 'طبيعة' },
  { word: 'شتاء', category: 'طبيعة' },
  { word: 'رمل', category: 'طبيعة' },
  { word: 'صخرة', category: 'طبيعة' },
  { word: 'تراب', category: 'طبيعة' },
  { word: 'طين', category: 'طبيعة' },
  { word: 'بركة', category: 'طبيعة' },
  { word: 'محيط', category: 'طبيعة' },
  { word: 'جزيرة', category: 'طبيعة' },
  { word: 'شاطئ', category: 'طبيعة' },
  { word: 'موجة', category: 'طبيعة' },
  { word: 'هواء', category: 'طبيعة' },
  { word: 'أرض', category: 'طبيعة' },
  { word: 'كوكب', category: 'طبيعة' },
  { word: 'مجرة', category: 'طبيعة' },
  { word: 'فضاء', category: 'طبيعة' },
  { word: 'نار', category: 'طبيعة' },
  
  // حيوانات - Animals (60 words)
  { word: 'أسد', category: 'حيوانات' },
  { word: 'نمر', category: 'حيوانات' },
  { word: 'فيل', category: 'حيوانات' },
  { word: 'زرافة', category: 'حيوانات' },
  { word: 'قطة', category: 'حيوانات' },
  { word: 'كلب', category: 'حيوانات' },
  { word: 'حصان', category: 'حيوانات' },
  { word: 'بقرة', category: 'حيوانات' },
  { word: 'خروف', category: 'حيوانات' },
  { word: 'ماعز', category: 'حيوانات' },
  { word: 'جمل', category: 'حيوانات' },
  { word: 'دب', category: 'حيوانات' },
  { word: 'ذئب', category: 'حيوانات' },
  { word: 'ثعلب', category: 'حيوانات' },
  { word: 'أرنب', category: 'حيوانات' },
  { word: 'غزال', category: 'حيوانات' },
  { word: 'فهد', category: 'حيوانات' },
  { word: 'قرد', category: 'حيوانات' },
  { word: 'حمار', category: 'حيوانات' },
  { word: 'بغل', category: 'حيوانات' },
  { word: 'طائر', category: 'حيوانات' },
  { word: 'عصفور', category: 'حيوانات' },
  { word: 'حمامة', category: 'حيوانات' },
  { word: 'نسر', category: 'حيوانات' },
  { word: 'صقر', category: 'حيوانات' },
  { word: 'بومة', category: 'حيوانات' },
  { word: 'ببغاء', category: 'حيوانات' },
  { word: 'ديك', category: 'حيوانات' },
  { word: 'دجاجة', category: 'حيوانات' },
  { word: 'بطة', category: 'حيوانات' },
  { word: 'أوزة', category: 'حيوانات' },
  { word: 'سمكة', category: 'حيوانات' },
  { word: 'قرش', category: 'حيوانات' },
  { word: 'حوت', category: 'حيوانات' },
  { word: 'دلفين', category: 'حيوانات' },
  { word: 'سلحفاة', category: 'حيوانات' },
  { word: 'تمساح', category: 'حيوانات' },
  { word: 'ثعبان', category: 'حيوانات' },
  { word: 'سحلية', category: 'حيوانات' },
  { word: 'ضفدع', category: 'حيوانات' },
  { word: 'نحلة', category: 'حيوانات' },
  { word: 'فراشة', category: 'حيوانات' },
  { word: 'نملة', category: 'حيوانات' },
  { word: 'عنكبوت', category: 'حيوانات' },
  { word: 'عقرب', category: 'حيوانات' },
  { word: 'ذبابة', category: 'حيوانات' },
  { word: 'بعوضة', category: 'حيوانات' },
  { word: 'صرصور', category: 'حيوانات' },
  { word: 'دودة', category: 'حيوانات' },
  { word: 'حلزون', category: 'حيوانات' },
  { word: 'أخطبوط', category: 'حيوانات' },
  { word: 'سرطان', category: 'حيوانات' },
  { word: 'محار', category: 'حيوانات' },
  { word: 'فقمة', category: 'حيوانات' },
  { word: 'بطريق', category: 'حيوانات' },
  { word: 'كنغر', category: 'حيوانات' },
  { word: 'باندا', category: 'حيوانات' },
  { word: 'وحيد', category: 'حيوانات' },
  { word: 'فرس', category: 'حيوانات' },
  
  // طعام - Food (50 words)
  { word: 'خبز', category: 'طعام' },
  { word: 'أرز', category: 'طعام' },
  { word: 'لحم', category: 'طعام' },
  { word: 'دجاج', category: 'طعام' },
  { word: 'سمك', category: 'طعام' },
  { word: 'بيض', category: 'طعام' },
  { word: 'جبن', category: 'طعام' },
  { word: 'حليب', category: 'طعام' },
  { word: 'زبدة', category: 'طعام' },
  { word: 'عسل', category: 'طعام' },
  { word: 'سكر', category: 'طعام' },
  { word: 'ملح', category: 'طعام' },
  { word: 'فلفل', category: 'طعام' },
  { word: 'ثوم', category: 'طعام' },
  { word: 'بصل', category: 'طعام' },
  { word: 'طماطم', category: 'طعام' },
  { word: 'خيار', category: 'طعام' },
  { word: 'جزر', category: 'طعام' },
  { word: 'بطاطس', category: 'طعام' },
  { word: 'باذنجان', category: 'طعام' },
  { word: 'كوسا', category: 'طعام' },
  { word: 'فاصوليا', category: 'طعام' },
  { word: 'عدس', category: 'طعام' },
  { word: 'حمص', category: 'طعام' },
  { word: 'فول', category: 'طعام' },
  { word: 'تفاح', category: 'طعام' },
  { word: 'برتقال', category: 'طعام' },
  { word: 'موز', category: 'طعام' },
  { word: 'عنب', category: 'طعام' },
  { word: 'تمر', category: 'طعام' },
  { word: 'تين', category: 'طعام' },
  { word: 'رمان', category: 'طعام' },
  { word: 'مانجو', category: 'طعام' },
  { word: 'أناناس', category: 'طعام' },
  { word: 'فراولة', category: 'طعام' },
  { word: 'بطيخ', category: 'طعام' },
  { word: 'شمام', category: 'طعام' },
  { word: 'ليمون', category: 'طعام' },
  { word: 'زيتون', category: 'طعام' },
  { word: 'لوز', category: 'طعام' },
  { word: 'جوز', category: 'طعام' },
  { word: 'فستق', category: 'طعام' },
  { word: 'شاي', category: 'طعام' },
  { word: 'قهوة', category: 'طعام' },
  { word: 'عصير', category: 'طعام' },
  { word: 'ماء', category: 'طعام' },
  { word: 'شوربة', category: 'طعام' },
  { word: 'سلطة', category: 'طعام' },
  { word: 'حلوى', category: 'طعام' },
  { word: 'كعكة', category: 'طعام' },
  
  // أماكن - Places (50 words)
  { word: 'بيت', category: 'أماكن' },
  { word: 'منزل', category: 'أماكن' },
  { word: 'شقة', category: 'أماكن' },
  { word: 'قصر', category: 'أماكن' },
  { word: 'فيلا', category: 'أماكن' },
  { word: 'كوخ', category: 'أماكن' },
  { word: 'خيمة', category: 'أماكن' },
  { word: 'مدرسة', category: 'أماكن' },
  { word: 'جامعة', category: 'أماكن' },
  { word: 'مكتبة', category: 'أماكن' },
  { word: 'مسجد', category: 'أماكن' },
  { word: 'كنيسة', category: 'أماكن' },
  { word: 'معبد', category: 'أماكن' },
  { word: 'مستشفى', category: 'أماكن' },
  { word: 'عيادة', category: 'أماكن' },
  { word: 'صيدلية', category: 'أماكن' },
  { word: 'سوق', category: 'أماكن' },
  { word: 'متجر', category: 'أماكن' },
  { word: 'مطعم', category: 'أماكن' },
  { word: 'مقهى', category: 'أماكن' },
  { word: 'فندق', category: 'أماكن' },
  { word: 'مطار', category: 'أماكن' },
  { word: 'ميناء', category: 'أماكن' },
  { word: 'محطة', category: 'أماكن' },
  { word: 'جسر', category: 'أماكن' },
  { word: 'نفق', category: 'أماكن' },
  { word: 'طريق', category: 'أماكن' },
  { word: 'شارع', category: 'أماكن' },
  { word: 'ساحة', category: 'أماكن' },
  { word: 'حديقة', category: 'أماكن' },
  { word: 'ملعب', category: 'أماكن' },
  { word: 'مسبح', category: 'أماكن' },
  { word: 'سينما', category: 'أماكن' },
  { word: 'مسرح', category: 'أماكن' },
  { word: 'متحف', category: 'أماكن' },
  { word: 'مصنع', category: 'أماكن' },
  { word: 'مكتب', category: 'أماكن' },
  { word: 'بنك', category: 'أماكن' },
  { word: 'سجن', category: 'أماكن' },
  { word: 'قلعة', category: 'أماكن' },
  { word: 'برج', category: 'أماكن' },
  { word: 'هرم', category: 'أماكن' },
  { word: 'مزرعة', category: 'أماكن' },
  { word: 'حقل', category: 'أماكن' },
  { word: 'بستان', category: 'أماكن' },
  { word: 'مدينة', category: 'أماكن' },
  { word: 'قرية', category: 'أماكن' },
  { word: 'دولة', category: 'أماكن' },
  { word: 'عاصمة', category: 'أماكن' },
  { word: 'حدود', category: 'أماكن' },
  
  // وسائل نقل - Transportation (25 words)
  { word: 'سيارة', category: 'وسائل نقل' },
  { word: 'حافلة', category: 'وسائل نقل' },
  { word: 'شاحنة', category: 'وسائل نقل' },
  { word: 'دراجة', category: 'وسائل نقل' },
  { word: 'قطار', category: 'وسائل نقل' },
  { word: 'طائرة', category: 'وسائل نقل' },
  { word: 'سفينة', category: 'وسائل نقل' },
  { word: 'قارب', category: 'وسائل نقل' },
  { word: 'يخت', category: 'وسائل نقل' },
  { word: 'مترو', category: 'وسائل نقل' },
  { word: 'تاكسي', category: 'وسائل نقل' },
  { word: 'سكوتر', category: 'وسائل نقل' },
  { word: 'عربة', category: 'وسائل نقل' },
  { word: 'مروحية', category: 'وسائل نقل' },
  { word: 'صاروخ', category: 'وسائل نقل' },
  { word: 'غواصة', category: 'وسائل نقل' },
  { word: 'بالون', category: 'وسائل نقل' },
  { word: 'زلاجة', category: 'وسائل نقل' },
  { word: 'مصعد', category: 'وسائل نقل' },
  { word: 'سلم', category: 'وسائل نقل' },
  { word: 'إطار', category: 'وسائل نقل' },
  { word: 'محرك', category: 'وسائل نقل' },
  { word: 'وقود', category: 'وسائل نقل' },
  { word: 'مقود', category: 'وسائل نقل' },
  { word: 'فرامل', category: 'وسائل نقل' },
  
  // مهن - Professions (40 words)
  { word: 'طبيب', category: 'مهن' },
  { word: 'ممرض', category: 'مهن' },
  { word: 'مهندس', category: 'مهن' },
  { word: 'معلم', category: 'مهن' },
  { word: 'محامي', category: 'مهن' },
  { word: 'قاضي', category: 'مهن' },
  { word: 'شرطي', category: 'مهن' },
  { word: 'جندي', category: 'مهن' },
  { word: 'طيار', category: 'مهن' },
  { word: 'بحار', category: 'مهن' },
  { word: 'سائق', category: 'مهن' },
  { word: 'طباخ', category: 'مهن' },
  { word: 'خباز', category: 'مهن' },
  { word: 'جزار', category: 'مهن' },
  { word: 'نجار', category: 'مهن' },
  { word: 'حداد', category: 'مهن' },
  { word: 'كهربائي', category: 'مهن' },
  { word: 'سباك', category: 'مهن' },
  { word: 'رسام', category: 'مهن' },
  { word: 'مصور', category: 'مهن' },
  { word: 'كاتب', category: 'مهن' },
  { word: 'صحفي', category: 'مهن' },
  { word: 'مذيع', category: 'مهن' },
  { word: 'ممثل', category: 'مهن' },
  { word: 'مغني', category: 'مهن' },
  { word: 'موسيقي', category: 'مهن' },
  { word: 'راقص', category: 'مهن' },
  { word: 'رياضي', category: 'مهن' },
  { word: 'مدرب', category: 'مهن' },
  { word: 'حارس', category: 'مهن' },
  { word: 'بائع', category: 'مهن' },
  { word: 'تاجر', category: 'مهن' },
  { word: 'مزارع', category: 'مهن' },
  { word: 'صياد', category: 'مهن' },
  { word: 'راعي', category: 'مهن' },
  { word: 'عالم', category: 'مهن' },
  { word: 'باحث', category: 'مهن' },
  { word: 'مترجم', category: 'مهن' },
  { word: 'خياط', category: 'مهن' },
  { word: 'حلاق', category: 'مهن' },
  
  // جسم الإنسان - Human Body (35 words)
  { word: 'رأس', category: 'جسم' },
  { word: 'وجه', category: 'جسم' },
  { word: 'عين', category: 'جسم' },
  { word: 'أنف', category: 'جسم' },
  { word: 'فم', category: 'جسم' },
  { word: 'أذن', category: 'جسم' },
  { word: 'شعر', category: 'جسم' },
  { word: 'جبين', category: 'جسم' },
  { word: 'خد', category: 'جسم' },
  { word: 'ذقن', category: 'جسم' },
  { word: 'رقبة', category: 'جسم' },
  { word: 'كتف', category: 'جسم' },
  { word: 'صدر', category: 'جسم' },
  { word: 'ظهر', category: 'جسم' },
  { word: 'بطن', category: 'جسم' },
  { word: 'يد', category: 'جسم' },
  { word: 'ذراع', category: 'جسم' },
  { word: 'كوع', category: 'جسم' },
  { word: 'معصم', category: 'جسم' },
  { word: 'إصبع', category: 'جسم' },
  { word: 'ظفر', category: 'جسم' },
  { word: 'ساق', category: 'جسم' },
  { word: 'ركبة', category: 'جسم' },
  { word: 'قدم', category: 'جسم' },
  { word: 'كعب', category: 'جسم' },
  { word: 'قلب', category: 'جسم' },
  { word: 'دماغ', category: 'جسم' },
  { word: 'رئة', category: 'جسم' },
  { word: 'كبد', category: 'جسم' },
  { word: 'معدة', category: 'جسم' },
  { word: 'كلية', category: 'جسم' },
  { word: 'عظم', category: 'جسم' },
  { word: 'عضلة', category: 'جسم' },
  { word: 'دم', category: 'جسم' },
  { word: 'جلد', category: 'جسم' },
  
  // أدوات وأشياء - Tools and Objects (50 words)
  { word: 'كتاب', category: 'أشياء' },
  { word: 'قلم', category: 'أشياء' },
  { word: 'ورقة', category: 'أشياء' },
  { word: 'دفتر', category: 'أشياء' },
  { word: 'حقيبة', category: 'أشياء' },
  { word: 'مفتاح', category: 'أشياء' },
  { word: 'قفل', category: 'أشياء' },
  { word: 'باب', category: 'أشياء' },
  { word: 'نافذة', category: 'أشياء' },
  { word: 'جدار', category: 'أشياء' },
  { word: 'سقف', category: 'أشياء' },
  { word: 'أرضية', category: 'أشياء' },
  { word: 'درج', category: 'أشياء' },
  { word: 'كرسي', category: 'أشياء' },
  { word: 'طاولة', category: 'أشياء' },
  { word: 'سرير', category: 'أشياء' },
  { word: 'خزانة', category: 'أشياء' },
  { word: 'مرآة', category: 'أشياء' },
  { word: 'ساعة', category: 'أشياء' },
  { word: 'هاتف', category: 'أشياء' },
  { word: 'حاسوب', category: 'أشياء' },
  { word: 'تلفاز', category: 'أشياء' },
  { word: 'راديو', category: 'أشياء' },
  { word: 'كاميرا', category: 'أشياء' },
  { word: 'مصباح', category: 'أشياء' },
  { word: 'شمعة', category: 'أشياء' },
  { word: 'مروحة', category: 'أشياء' },
  { word: 'ثلاجة', category: 'أشياء' },
  { word: 'فرن', category: 'أشياء' },
  { word: 'غسالة', category: 'أشياء' },
  { word: 'مكنسة', category: 'أشياء' },
  { word: 'سكين', category: 'أشياء' },
  { word: 'شوكة', category: 'أشياء' },
  { word: 'ملعقة', category: 'أشياء' },
  { word: 'صحن', category: 'أشياء' },
  { word: 'كوب', category: 'أشياء' },
  { word: 'إبريق', category: 'أشياء' },
  { word: 'قدر', category: 'أشياء' },
  { word: 'مقلاة', category: 'أشياء' },
  { word: 'ملابس', category: 'أشياء' },
  { word: 'قميص', category: 'أشياء' },
  { word: 'بنطلون', category: 'أشياء' },
  { word: 'فستان', category: 'أشياء' },
  { word: 'معطف', category: 'أشياء' },
  { word: 'حذاء', category: 'أشياء' },
  { word: 'جوارب', category: 'أشياء' },
  { word: 'قبعة', category: 'أشياء' },
  { word: 'نظارة', category: 'أشياء' },
  { word: 'خاتم', category: 'أشياء' },
  { word: 'سلسلة', category: 'أشياء' },
  
  // مشاعر وأحاسيس - Emotions (30 words)
  { word: 'حب', category: 'مشاعر' },
  { word: 'كره', category: 'مشاعر' },
  { word: 'فرح', category: 'مشاعر' },
  { word: 'حزن', category: 'مشاعر' },
  { word: 'غضب', category: 'مشاعر' },
  { word: 'خوف', category: 'مشاعر' },
  { word: 'قلق', category: 'مشاعر' },
  { word: 'أمل', category: 'مشاعر' },
  { word: 'يأس', category: 'مشاعر' },
  { word: 'سعادة', category: 'مشاعر' },
  { word: 'تعاسة', category: 'مشاعر' },
  { word: 'حماس', category: 'مشاعر' },
  { word: 'ملل', category: 'مشاعر' },
  { word: 'دهشة', category: 'مشاعر' },
  { word: 'حيرة', category: 'مشاعر' },
  { word: 'ثقة', category: 'مشاعر' },
  { word: 'شك', category: 'مشاعر' },
  { word: 'فخر', category: 'مشاعر' },
  { word: 'خجل', category: 'مشاعر' },
  { word: 'غيرة', category: 'مشاعر' },
  { word: 'حسد', category: 'مشاعر' },
  { word: 'رحمة', category: 'مشاعر' },
  { word: 'شفقة', category: 'مشاعر' },
  { word: 'عطف', category: 'مشاعر' },
  { word: 'احترام', category: 'مشاعر' },
  { word: 'إعجاب', category: 'مشاعر' },
  { word: 'شوق', category: 'مشاعر' },
  { word: 'حنين', category: 'مشاعر' },
  { word: 'راحة', category: 'مشاعر' },
  { word: 'توتر', category: 'مشاعر' },
  
  // مفاهيم ومجردات - Concepts (40 words)
  { word: 'حرية', category: 'مفاهيم' },
  { word: 'عدالة', category: 'مفاهيم' },
  { word: 'سلام', category: 'مفاهيم' },
  { word: 'حرب', category: 'مفاهيم' },
  { word: 'صداقة', category: 'مفاهيم' },
  { word: 'عداوة', category: 'مفاهيم' },
  { word: 'نجاح', category: 'مفاهيم' },
  { word: 'فشل', category: 'مفاهيم' },
  { word: 'حياة', category: 'مفاهيم' },
  { word: 'موت', category: 'مفاهيم' },
  { word: 'صحة', category: 'مفاهيم' },
  { word: 'مرض', category: 'مفاهيم' },
  { word: 'قوة', category: 'مفاهيم' },
  { word: 'ضعف', category: 'مفاهيم' },
  { word: 'غنى', category: 'مفاهيم' },
  { word: 'فقر', category: 'مفاهيم' },
  { word: 'علم', category: 'مفاهيم' },
  { word: 'جهل', category: 'مفاهيم' },
  { word: 'حقيقة', category: 'مفاهيم' },
  { word: 'كذب', category: 'مفاهيم' },
  { word: 'صدق', category: 'مفاهيم' },
  { word: 'خيانة', category: 'مفاهيم' },
  { word: 'وفاء', category: 'مفاهيم' },
  { word: 'شجاعة', category: 'مفاهيم' },
  { word: 'جبن', category: 'مفاهيم' },
  { word: 'كرم', category: 'مفاهيم' },
  { word: 'بخل', category: 'مفاهيم' },
  { word: 'تواضع', category: 'مفاهيم' },
  { word: 'كبرياء', category: 'مفاهيم' },
  { word: 'صبر', category: 'مفاهيم' },
  { word: 'عجلة', category: 'مفاهيم' },
  { word: 'حكمة', category: 'مفاهيم' },
  { word: 'غباء', category: 'مفاهيم' },
  { word: 'جمال', category: 'مفاهيم' },
  { word: 'قبح', category: 'مفاهيم' },
  { word: 'نظام', category: 'مفاهيم' },
  { word: 'فوضى', category: 'مفاهيم' },
  { word: 'وقت', category: 'مفاهيم' },
  { word: 'مكان', category: 'مفاهيم' },
  { word: 'ذاكرة', category: 'مفاهيم' },
  
  // عائلة وعلاقات - Family and Relations (25 words)
  { word: 'أب', category: 'عائلة' },
  { word: 'أم', category: 'عائلة' },
  { word: 'ابن', category: 'عائلة' },
  { word: 'ابنة', category: 'عائلة' },
  { word: 'أخ', category: 'عائلة' },
  { word: 'أخت', category: 'عائلة' },
  { word: 'جد', category: 'عائلة' },
  { word: 'جدة', category: 'عائلة' },
  { word: 'عم', category: 'عائلة' },
  { word: 'عمة', category: 'عائلة' },
  { word: 'خال', category: 'عائلة' },
  { word: 'خالة', category: 'عائلة' },
  { word: 'زوج', category: 'عائلة' },
  { word: 'زوجة', category: 'عائلة' },
  { word: 'صديق', category: 'عائلة' },
  { word: 'صديقة', category: 'عائلة' },
  { word: 'جار', category: 'عائلة' },
  { word: 'ضيف', category: 'عائلة' },
  { word: 'طفل', category: 'عائلة' },
  { word: 'شاب', category: 'عائلة' },
  { word: 'شابة', category: 'عائلة' },
  { word: 'رجل', category: 'عائلة' },
  { word: 'امرأة', category: 'عائلة' },
  { word: 'عجوز', category: 'عائلة' },
  { word: 'يتيم', category: 'عائلة' },
  
  // رياضة وألعاب - Sports and Games (25 words)
  { word: 'كرة', category: 'رياضة' },
  { word: 'ملعب', category: 'رياضة' },
  { word: 'فريق', category: 'رياضة' },
  { word: 'هدف', category: 'رياضة' },
  { word: 'فوز', category: 'رياضة' },
  { word: 'خسارة', category: 'رياضة' },
  { word: 'تعادل', category: 'رياضة' },
  { word: 'بطولة', category: 'رياضة' },
  { word: 'ميدالية', category: 'رياضة' },
  { word: 'كأس', category: 'رياضة' },
  { word: 'سباق', category: 'رياضة' },
  { word: 'سباحة', category: 'رياضة' },
  { word: 'جري', category: 'رياضة' },
  { word: 'قفز', category: 'رياضة' },
  { word: 'رمي', category: 'رياضة' },
  { word: 'ملاكمة', category: 'رياضة' },
  { word: 'مصارعة', category: 'رياضة' },
  { word: 'تنس', category: 'رياضة' },
  { word: 'شطرنج', category: 'رياضة' },
  { word: 'ورق', category: 'رياضة' },
  { word: 'نرد', category: 'رياضة' },
  { word: 'لعبة', category: 'رياضة' },
  { word: 'دمية', category: 'رياضة' },
  { word: 'أرجوحة', category: 'رياضة' },
  { word: 'زحليقة', category: 'رياضة' },
  
  // فنون وثقافة - Arts and Culture (20 words)
  { word: 'موسيقى', category: 'فنون' },
  { word: 'أغنية', category: 'فنون' },
  { word: 'رقص', category: 'فنون' },
  { word: 'رسم', category: 'فنون' },
  { word: 'لوحة', category: 'فنون' },
  { word: 'تمثال', category: 'فنون' },
  { word: 'شعر', category: 'فنون' },
  { word: 'قصة', category: 'فنون' },
  { word: 'رواية', category: 'فنون' },
  { word: 'مسرحية', category: 'فنون' },
  { word: 'فيلم', category: 'فنون' },
  { word: 'مسلسل', category: 'فنون' },
  { word: 'عود', category: 'فنون' },
  { word: 'طبلة', category: 'فنون' },
  { word: 'ناي', category: 'فنون' },
  { word: 'بيانو', category: 'فنون' },
  { word: 'كمان', category: 'فنون' },
  { word: 'قيثارة', category: 'فنون' },
  { word: 'ريشة', category: 'فنون' },
  { word: 'ألوان', category: 'فنون' },
]

// Generate a deterministic word based on date
export function getWordForDate(dateString: string): WordData {
  // Create a simple hash from the date string
  let hash = 0
  for (let i = 0; i < dateString.length; i++) {
    const char = dateString.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash // Convert to 32-bit integer
  }
  
  // Use absolute value and modulo to get index
  const index = Math.abs(hash) % ARABIC_WORDS.length
  return ARABIC_WORDS[index]
}

export function getTodayDateString(): string {
  const today = new Date()
  return `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`
}
